### ISSUE TITLE
BUG day magma, lava etc.

### ISSUE THREAD

**Issue by ShrikerChestTree** [fewizz/lomo#1]
When the Day is in Minecraft, the blocks that you added appear as black squares, and at night everything is fine!

**Comment by fewizz** [comment]
Please, provide screenshot, minecraft, canvas and lomo version.

**Comment by ShrikerChestTree** [comment]
![2022-10-16_16 21 53](https://user-images.githubusercontent.com/107254774/196037852-0682fa39-8225-4ea0-b9fa-8caea4a1af14.png)
Version
Minecraft 1.19.2
Canvas 1.0.2487
lomo 0.10.0

**Comment by fewizz** [comment]
[lomo.zip](https://github.com/fewizz/lomo/files/9794785/lomo.zip)
you can try this version, latest one (which isn't released yet). also, would be cool to know your gpu/driver/system

**Comment by ShrikerChestTree** [comment]
That's exactly why I can't download the latest version :(

**Comment by fewizz** [comment]
not sure what do you mean by that, but вы можете написать мне в дис: fewizz#3328

**Comment by ShrikerChestTree** [comment]
OK

**Comment by ShrikerChestTree** [comment]
My nickname Discord SCT

**Comment by fewizz** [comment]
fixed with 0.11.1+.

**Comment by ShrikerChestTree** [comment]
> fixed with 0.11.1+.

OK
